import type { Metadata } from "next";
import "./styles/reset/reset.scss";
import Dashboard from "./components/dashboard/dashboard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Dashboard />
        {children}
      </body>
    </html>
  );
}
